# Generated by Django 3.2.3 on 2021-07-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('G', 'Video Game'), ('B', 'Book'), ('A', 'Anime')], default='A', max_length=1)),
                ('description', models.TextField(max_length=250)),
                ('waifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.waifu')),
            ],
        ),
    ]
